name: Build and push to TdA

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        uses: docker/build-push-action@v6.8.0
        with:
          context: ./
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: tda:latest
          outputs: type=docker,dest=/tmp/tda.tar
          # Pokud máte Dockerfile v konkrétní složce, například /php, nastavte context podle toho
          dockerfile: ./Dockerfile   # Ujistěte se, že máte správnou cestu k Dockerfile, pokud je v jiné složce

      - name: Upload to TdA
        uses: Tour-de-App/upload-app@tda-25
        with:
          team_token: ${{ secrets.TEAM_TOKEN }}
          image_name: tda
          image_path: /tmp/tda.tar
